"""
PlatformIO pre-build script: auto-generate include/version.h
with git commit count, short hash, and build timestamp.

Version format:  MAJOR.MINOR.COMMIT_COUNT+SHORT_HASH  (BUILD_TIMESTAMP)
Example:         1.4.21+ae15310 (2026-02-26 14:30)

MAJOR and MINOR are set manually below.  Everything else is automatic.
"""

import subprocess
import datetime
import os

# ── Manual version parts (bump these by hand when you want) ──────────
VERSION_MAJOR = 3
VERSION_MINOR = 0
# ─────────────────────────────────────────────────────────────────────

# Resolve the project root directory.
# When run inside PlatformIO/SCons, __file__ is not defined, so we fall
# back to the current working directory (PlatformIO sets cwd to the
# project root).  env["PROJECT_DIR"] is passed in when available.
def _get_project_dir(env=None):
    if env is not None:
        try:
            return env["PROJECT_DIR"]
        except (KeyError, TypeError):
            pass
    try:
        return os.path.dirname(os.path.abspath(__file__))
    except NameError:
        return os.getcwd()


def git_value(project_dir, *args):
    """Run a git command and return stripped stdout, or None on failure."""
    try:
        result = subprocess.run(
            ["git"] + list(args),
            capture_output=True, text=True, check=True,
            cwd=project_dir,
        )
        return result.stdout.strip()
    except Exception:
        return None

def generate_version_header(env=None):
    project_dir = _get_project_dir(env)
    commit_count = git_value(project_dir, "rev-list", "--count", "HEAD") or "0"
    short_hash   = git_value(project_dir, "rev-parse", "--short", "HEAD") or "unknown"
    # Check for uncommitted changes
    dirty = ""
    status = git_value(project_dir, "status", "--porcelain")
    if status:  # non-empty means uncommitted changes
        dirty = "-dirty"
    build_ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    version_str = (
        f"{VERSION_MAJOR}.{VERSION_MINOR}.{commit_count}+{short_hash}{dirty}"
    )
    full_version = f"{version_str} ({build_ts})"

    header = f"""// Auto-generated by version_build.py — DO NOT EDIT
#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR    {VERSION_MAJOR}
#define VERSION_MINOR    {VERSION_MINOR}
#define VERSION_PATCH    {commit_count}
#define VERSION_HASH     "{short_hash}"
#define VERSION_DIRTY    "{dirty}"
#define VERSION_BUILD_TS "{build_ts}"
#define VERSION_STRING   "{version_str}"
#define VERSION_FULL     "{full_version}"

#endif // VERSION_H
"""

    header_path = os.path.join(project_dir, "include", "version.h")
    # Only write if content changed (avoids unnecessary rebuilds)
    if os.path.exists(header_path):
        with open(header_path, "r") as f:
            if f.read() == header:
                print(f"version_build.py: version unchanged ({version_str})")
                return
    with open(header_path, "w") as f:
        f.write(header)
    print(f"version_build.py: generated version {full_version}")

# When run by PlatformIO, Import("env") is available.
# When run standalone (e.g. `python version_build.py`), just call directly.
try:
    Import("env")          # noqa: F821  (PlatformIO built-in)
    generate_version_header(env)
except NameError:
    # Standalone execution
    generate_version_header()
